version: '3'

services:
  ollama-app:
    build:
      context: ./image
    ports:
      - "11434:11434"
    volumes:
      - /mnt/nvme1/ollama-dir:/root/.ollama:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
