version: '3'

services:
  ollama-app:
    build:
      context: ./image
    ports:
      - "11434:11434"
    volumes:
      - /mnt/nvme1/ollama-dir:/root/.ollama:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: http://10.1.1.9:11434

  langchain-env:
    build:
      context: ./langchain-image
    ports:
      - "5555:5000"

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      - N8N_SECURE_COOKIE=false
    ports:
      - "5699:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
